POST http://localhost:3003/api/blogs/5e834be80aec380e00638fdb/comments
Content-Type: application/json

{
  "comment": "Interesting post. I went through a similar thinking process and I ended up with the same result: an `id -> entity` map and then use `reselect` to create a model to satisfy my view requirements."
}
