POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhbWlncmVlbiIsImlkIjoiNWU2NGVkM2EyNjY0NjkwY2I4YTRjOWFiIiwiaWF0IjoxNTgzNjczNjE5fQ.Xp7-ltx6lPNymfhChqedqK0s_k6mxwDgyLOzljDn-x0

{
  "title": "How to hjdff sdd  llraod",
  "arthur": "gur jiokret",
  "url": "www.playershandbook.com",
  "likes": 3
}