POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Wwabi parker",
    "dateOfBirth": "1930-09-29",
    "ssn": "992891-122X",
    "gender": "male",
    "occupation": "Fashion Designer"
}
